# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest as db 

# Set environment variables for PostgreSQL
# [TODO]: put in .env file
ARG POSTGRES_USER
ENV POSTGRES_USER=$POSTGRES_USER
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ARG POSTGRES_DB
ENV POSTGRES_DB=$POSTGRES_DB

# Expose the default PostgreSQL port
EXPOSE 5432
